# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WinfsInjector < Formula
  desc ""
  homepage ""
  version "0.20.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.20.0/winfs-injector-darwin-0.20.0.tar.gz"
      sha256 "e1122912f32a099c1e02e41e51373699220758d54c6df7776d50ff8ca1d7fc99"

      def install
        bin.install "winfs-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.20.0/winfs-injector-linux-0.20.0.tar.gz"
      sha256 "a841aba6fbb5dbea45e2c446fe8ce2d6c1c31568499bceacf9da134780050514"

      def install
        bin.install "winfs-injector"
      end
    end
  end

  test do
    system "#{bin}/winfs-injector --version"
  end
end
