# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WinfsInjector < Formula
  desc ""
  homepage ""
  version "0.21.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.21.0/winfs-injector-darwin.tar.gz"
      sha256 "012691194ce39d59a6babad97effe5b386f0d0232da6deb59db4fdd94f11ba5e"

      def install
        bin.install "winfs-injector"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/pivotal-cf/winfs-injector/releases/download/0.21.0/winfs-injector-linux.tar.gz"
      sha256 "2831b4c93678550272fe4c77dc62bc0482a4189d606a64a56da0669fc3ccccb8"

      def install
        bin.install "winfs-injector"
      end
    end
  end

  test do
    system "#{bin}/winfs-injector --version"
  end
end
