// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	sync "sync"
)

type Zipper struct {
	UnzipStub        func(string, string) error
	unzipMutex       sync.RWMutex
	unzipArgsForCall []struct {
		arg1 string
		arg2 string
	}
	unzipReturns struct {
		result1 error
	}
	unzipReturnsOnCall map[int]struct {
		result1 error
	}
	ZipStub        func(string, string) error
	zipMutex       sync.RWMutex
	zipArgsForCall []struct {
		arg1 string
		arg2 string
	}
	zipReturns struct {
		result1 error
	}
	zipReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *Zipper) Unzip(arg1 string, arg2 string) error {
	fake.unzipMutex.Lock()
	ret, specificReturn := fake.unzipReturnsOnCall[len(fake.unzipArgsForCall)]
	fake.unzipArgsForCall = append(fake.unzipArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("Unzip", []interface{}{arg1, arg2})
	fake.unzipMutex.Unlock()
	if fake.UnzipStub != nil {
		return fake.UnzipStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.unzipReturns
	return fakeReturns.result1
}

func (fake *Zipper) UnzipCallCount() int {
	fake.unzipMutex.RLock()
	defer fake.unzipMutex.RUnlock()
	return len(fake.unzipArgsForCall)
}

func (fake *Zipper) UnzipCalls(stub func(string, string) error) {
	fake.unzipMutex.Lock()
	defer fake.unzipMutex.Unlock()
	fake.UnzipStub = stub
}

func (fake *Zipper) UnzipArgsForCall(i int) (string, string) {
	fake.unzipMutex.RLock()
	defer fake.unzipMutex.RUnlock()
	argsForCall := fake.unzipArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Zipper) UnzipReturns(result1 error) {
	fake.unzipMutex.Lock()
	defer fake.unzipMutex.Unlock()
	fake.UnzipStub = nil
	fake.unzipReturns = struct {
		result1 error
	}{result1}
}

func (fake *Zipper) UnzipReturnsOnCall(i int, result1 error) {
	fake.unzipMutex.Lock()
	defer fake.unzipMutex.Unlock()
	fake.UnzipStub = nil
	if fake.unzipReturnsOnCall == nil {
		fake.unzipReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unzipReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Zipper) Zip(arg1 string, arg2 string) error {
	fake.zipMutex.Lock()
	ret, specificReturn := fake.zipReturnsOnCall[len(fake.zipArgsForCall)]
	fake.zipArgsForCall = append(fake.zipArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("Zip", []interface{}{arg1, arg2})
	fake.zipMutex.Unlock()
	if fake.ZipStub != nil {
		return fake.ZipStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.zipReturns
	return fakeReturns.result1
}

func (fake *Zipper) ZipCallCount() int {
	fake.zipMutex.RLock()
	defer fake.zipMutex.RUnlock()
	return len(fake.zipArgsForCall)
}

func (fake *Zipper) ZipCalls(stub func(string, string) error) {
	fake.zipMutex.Lock()
	defer fake.zipMutex.Unlock()
	fake.ZipStub = stub
}

func (fake *Zipper) ZipArgsForCall(i int) (string, string) {
	fake.zipMutex.RLock()
	defer fake.zipMutex.RUnlock()
	argsForCall := fake.zipArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *Zipper) ZipReturns(result1 error) {
	fake.zipMutex.Lock()
	defer fake.zipMutex.Unlock()
	fake.ZipStub = nil
	fake.zipReturns = struct {
		result1 error
	}{result1}
}

func (fake *Zipper) ZipReturnsOnCall(i int, result1 error) {
	fake.zipMutex.Lock()
	defer fake.zipMutex.Unlock()
	fake.ZipStub = nil
	if fake.zipReturnsOnCall == nil {
		fake.zipReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.zipReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *Zipper) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.unzipMutex.RLock()
	defer fake.unzipMutex.RUnlock()
	fake.zipMutex.RLock()
	defer fake.zipMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *Zipper) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
